<a href="https://colab.research.google.com/github/TanishkAgrawal/AI-Project-/blob/main/AI_Project3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# New section

In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [25]:
df = pd.read_csv("/content/Suicidal_tweet_dataset.csv")
dataset = pd.DataFrame(df)
dataset

,Unnamed: 0,text,class
0,74414,dont know7 month self harm free urg get strong...,suicide
1,149516,start becom rich start compani becom 16 afford...,non-suicide
2,12484,poem haiku umegamedev hi hello hello stop fuck...,non-suicide
3,14043,ive honestli got idea anymoreit feel everyon f...,suicide
4,30673,ever cri like think unfair life cri cant cri e...,non-suicide
...,...,...,...
9995,72380,teenag femal like decis teenag femal make movi...,non-suicide
9996,62872,watch english teacher crash burn highlight mor...,non-suicide
9997,115556,controli feel like everyon tell live day day c...,suicide
9998,128606,keep nightmar trigger warn nightmar 1 stitch a...,non-suicide
9999,224640,im lone bore need someon talk im 14m,non-suicide

In [26]:
dataset.head

<bound method NDFrame.head of       Unnamed: 0                                               text  \
0          74414  dont know7 month self harm free urg get strong...
1         149516  start becom rich start compani becom 16 afford...
2          12484  poem haiku umegamedev hi hello hello stop fuck...
3          14043  ive honestli got idea anymoreit feel everyon f...
4          30673  ever cri like think unfair life cri cant cri e...
...          ...                                                ...
9995       72380  teenag femal like decis teenag femal make movi...
9996       62872  watch english teacher crash burn highlight mor...
9997      115556  controli feel like everyon tell live day day c...
9998      128606  keep nightmar trigger warn nightmar 1 stitch a...
9999      224640               im lone bore need someon talk im 14m

            class
0         suicide
1     non-suicide
2     non-suicide
3         suicide
4     non-suicide
...           ...
9995  non-suicide
9996  non-suicide
9997      suicide
9998  non-suicide
9999  non-suicide

[10000 rows x 3 columns]>

In [27]:
dataset.describe()

          Unnamed: 0
count   10000.000000
mean   116175.102200
std     67086.348973
min        33.000000
25%     58059.750000
50%    116240.500000
75%    174133.250000
max    232071.000000

In [28]:
dataset.shape

(10000, 3)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10000 non-null  int64
 1   text        9999 non-null   object
 2   class       10000 non-null  object
dtypes: int64(1), object(2)
memory usage: 234.5+ KB

In [30]:
dataset.loc[dataset['class'] == 'suicide', 'class',] = 0
dataset.loc[dataset['class'] == 'non-suicide', 'class',] = 1

In [31]:
dataset.head

<bound method NDFrame.head of       Unnamed: 0                                               text class
0          74414  dont know7 month self harm free urg get strong...     0
1         149516  start becom rich start compani becom 16 afford...     1
2          12484  poem haiku umegamedev hi hello hello stop fuck...     1
3          14043  ive honestli got idea anymoreit feel everyon f...     0
4          30673  ever cri like think unfair life cri cant cri e...     1
...          ...                                                ...   ...
9995       72380  teenag femal like decis teenag femal make movi...     1
9996       62872  watch english teacher crash burn highlight mor...     1
9997      115556  controli feel like everyon tell live day day c...     0
9998      128606  keep nightmar trigger warn nightmar 1 stitch a...     1
9999      224640               im lone bore need someon talk im 14m     1

[10000 rows x 3 columns]>

In [32]:
X = dataset['text']
Y = dataset['class']

In [33]:
X.head

<bound method NDFrame.head of 0       dont know7 month self harm free urg get strong...
1       start becom rich start compani becom 16 afford...
2       poem haiku umegamedev hi hello hello stop fuck...
3       ive honestli got idea anymoreit feel everyon f...
4       ever cri like think unfair life cri cant cri e...
                              ...
9995    teenag femal like decis teenag femal make movi...
9996    watch english teacher crash burn highlight mor...
9997    controli feel like everyon tell live day day c...
9998    keep nightmar trigger warn nightmar 1 stitch a...
9999                 im lone bore need someon talk im 14m
Name: text, Length: 10000, dtype: object>

In [34]:
Y.head

<bound method NDFrame.head of 0       0
1       1
2       1
3       0
4       1
       ..
9995    1
9996    1
9997    0
9998    1
9999    1
Name: class, Length: 10000, dtype: object>

In [35]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size = 0.25, random_state = 17
)

In [36]:
x_train = [text for text in x_train if isinstance(text, str)]
x_test = [text for text in x_test if isinstance(text, str)]

In [37]:
x_train = pd.Series(x_train).fillna("").tolist()
x_test = pd.Series(x_test).fillna("").tolist()

In [38]:
import pandas as pd
y_train = pd.Series(y_train).dropna()

In [39]:
from sklearn.feature_extraction.text import TfidfVectorizer
Vectorizer = TfidfVectorizer(min_df = 1, stop_words='english', lowercase = True)
X_train = Vectorizer.fit_transform(x_train)
X_test = Vectorizer.transform(x_test)

y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [40]:
print(X_train.shape)
print(y_train.shape)

(7499, 19596)
(7500,)

In [41]:
if len(y_train) > X_train.shape[0]:
    y_train = y_train[:X_train.shape[0]]

In [42]:
import xgboost as xgb
model = xgb.XGBClassifier()
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [43]:
prediction = model.predict(X_test)

In [44]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, prediction)
score

0.8864